Repository aragon/aragonOS, pull requests merged in 2018-10, with the labels that each got.

#434 Change EVMScriptRegistry executor storage from an array to mapping
  contracts/evmscript/EVMScriptRegistry.sol
Labels: enhancement

#433 Remove redundant kernel check in AragonApp.getRecoveryVault()
  contracts/apps/AragonApp.sol
Labels: enhancement

#437 Make EVMScriptRegistryFactory optional for DAO factory
  scripts/deploy-daofactory.js
Labels: epic: dev tooling, status: quick-review-and-merge

#444 Clarify intention around usage of isContract
  contracts/common/IsContract.sol
Labels: type: docs

#447 Change devnet (docker image) network id
  truffle-config.js
Labels: status: quick-review-and-merge

#452 chore EVMScriptRegistryFactory: remove unused AppProxyFactory base contract
  contracts/factory/EVMScriptRegistryFactory.sol
Labels: enhancement, status: quick-review-and-merge
