Repository aragon/aragonOS, pull requests merged in 2018-06, with the labels that each got.

#317 Use npx everywhere
  package.json
  scripts/ganache-cli.sh
Labels: meta, status: quick-review-and-merge

#329 Truffle console is now truffle dev
  package.json
Labels: epic: audit, sprint: 0.5.2

#343 Fix import in KeccakConstants test mock
  test/mocks/KeccakConstants.sol
Labels: status: quick-review-and-merge

#345 Make ANY_ENTITY from ACL constant accessible
  contracts/acl/ACL.sol
Labels: status: quick-review-and-merge
