Repository aragon/aragonOS, pull requests merged in 2018-03, with the labels that each got.

#243 Minor changes for deployment with docker
  package-lock.json
  package.json
  scripts/deploy-beta-apm.js
  scripts/deploy-beta-ens.js
  truffle-config.js
Labels: status: quick-review-and-merge

#248 delegatecall safety: Implement min return size in DelegateProxy
  contracts/common/DelegateProxy.sol
  test/TestDelegateProxy.sol
  test/helpers/ThrowProxy.sol
Labels: priority: asap, status: quick-review-and-merge

#257 Fix storage shadowing in DeployDelegateScript cache
  contracts/evmscript/executors/DeployDelegateScript.sol
Labels: status: quick-review-and-merge

#268 ENSFactory: import ENSConstants instead of ENSSubdomainRegistrar
  contracts/factory/ENSFactory.sol
Labels: audit: whg

#270 AragonApp: add comments for inheriting from ACLSyntaxSugar, EVMScriptRunner
  contracts/apps/AragonApp.sol
Labels: audit: whg

#271 DAOFactory: remove unnecessary ternary
  contracts/factory/DAOFactory.sol
Labels: audit: whg
