Repository aragon/aragonOS, pull requests merged in 2018-09, with the labels that each got.

#410 Kernel: use explicit mapping for namespaces rather than hash
  contracts/apps/AppProxyBase.sol
  contracts/evmscript/EVMScriptRunner.sol
  contracts/evmscript/IEVMScriptRegistry.sol
  contracts/kernel/IKernel.sol
  contracts/kernel/Kernel.sol
  contracts/kernel/KernelConstants.sol
  contracts/kernel/KernelProxy.sol
  contracts/kernel/KernelStorage.sol
  contracts/test/mocks/KeccakConstants.sol
  contracts/test/mocks/KernelSetAppMock.sol
  test/keccak_constants.js
  test/kernel_apps.js
  test/kernel_lifecycle.js
  test/proxy_recover_funds.js
Labels: breaking-change

#414 Clean up truffle-config.js and lazy load providers
  truffle-config.js
Labels: epic: in sprint addition

#416 Modular deployment scripts
  scripts/deploy-beta-apm.js
  scripts/deploy-beta-ens.js
  scripts/deploy-daofactory.js
Labels: epic: in sprint addition

#413 Remove migrations and revamp scripts
  migrations/2_apm.js
  migrations/3_factory.js
  package.json
  scripts/deploy-beta-apm.js
  scripts/deploy-beta-ens.js
  scripts/deploy-daofactory.js
Labels: epic: in sprint addition

#412 ACL: add more tests about initialization
  test/kernel_acl.js
Labels: acl, epic: in sprint addition

#415 Kernel: allow initializing app proxies on overloaded newAppInstance
  contracts/factory/APMRegistryFactory.sol
  contracts/factory/EVMScriptRegistryFactory.sol
  contracts/kernel/Kernel.sol
  contracts/test/mocks/APMRegistryFactoryMock.sol
  contracts/test/mocks/KernelOverloadMock.sol
  test/kernel_apps.js
Labels: epic: in sprint addition

#408 ACL: use TimeHelpers
  contracts/acl/ACL.sol
Labels: epic: audit

#401 Add ability to enable / disable depositable functionality
  .solcover.js
  contracts/common/DepositableDelegateProxy.sol
  contracts/common/DepositableStorage.sol
  contracts/common/UnstructuredStorage.sol
  contracts/factory/DAOFactory.sol
  contracts/test/mocks/AppProxyPinnedStorageMock.sol
  contracts/test/mocks/AppStorageMock.sol
  contracts/test/mocks/AppStub.sol
  contracts/test/mocks/AppStubConditionalRecovery.sol
  contracts/test/mocks/AppStubDepositable.sol
  contracts/test/mocks/DepositableStorageMock.sol
  contracts/test/mocks/InitializableStorageMock.sol
  contracts/test/mocks/KeccakConstants.sol
  contracts/test/mocks/KernelDepositableMock.sol
  contracts/test/mocks/VaultMock.sol
  test/app_funds.js
  test/keccak_constants.js
  test/kernel_funds.js
  test/proxy_recover_funds.js
  test/unstructured_storage.js
Labels: epic: audit

#417 lib: optimize multiplication for SafeMath64 and SafeMath8
  contracts/lib/math/SafeMath64.sol
  contracts/lib/math/SafeMath8.sol
  contracts/test/mocks/SafeMath64Mock.sol
  contracts/test/mocks/SafeMath8Mock.sol
  test/lib_safemath64.js
  test/lib_safemath8.js
Labels: epic: audit, epic: in sprint addition

#425 Add test for recevering ETH from Kernel
  test/proxy_recover_funds.js
Labels: audit: cd, audit: whg, epic: audit

#430 Change Repo version storage from an array to a mapping
  contracts/apm/Repo.sol
Labels: apm, enhancement

#429 Add `petrifyPermission` function to ACL
  contracts/acl/ACL.sol
  test/helpers/assertEvent.js
  test/kernel_acl.js
Labels: acl, enhancement
