Repository aragon/aragonOS, pull requests merged in 2018-08, with the labels that each got.

#377 Add helper to `ACLSyntaxSugar`
  contracts/acl/ACLSyntaxSugar.sol
Labels: acl, enhancement, epic: in sprint addition, sprint: 0.5.4, status: quick-review-and-merge

#372 Tests: setting default apps via newAppInstance
  package.json
  test/kernel_acl.js
  test/kernel_apps.js
  test/mocks/KernelMock.sol
Labels: epic: in sprint addition, sprint: 0.5.4

#375 Uint and Time helpers
  contracts/common/Initializable.sol
  contracts/common/TimeHelpers.sol
  contracts/common/Uint256Helpers.sol
  test/lib_uint256_helpers.js
  test/mocks/TimeHelpersMock.sol
  test/mocks/Uint256Mock.sol
  test/time_helpers.js
Labels: audit: cd, epic: audit, sprint: 0.5.4

#353 Update SafeMath libraries to their current gas-optimized versions
  contracts/lib/zeppelin/math/SafeMath.sol
  contracts/lib/zeppelin/math/SafeMath64.sol
  contracts/lib/zeppelin/math/SafeMath8.sol
Labels: epic: in sprint addition, sprint: 0.5.3, sprint: 0.5.4

#362 ACL: log whether a permission was set with parameters
  contracts/acl/ACL.sol
  test/kernel_acl.js
Labels: sprint: 0.5.3, sprint: 0.5.4

#381 Make time helper tests more robust by giving a bit of leeway
  test/time_helpers.js
Labels: epic: in sprint addition, sprint: 0.5.5

#380 Make UnstructuredStorage a library
  contracts/apps/AppProxyPinned.sol
  contracts/apps/AppStorage.sol
  contracts/common/Initializable.sol
  contracts/common/UnstructuredStorage.sol
  migrations/2_apm.js
  test/apm_registry.js
  test/ens_subdomains.js
  test/keccak_constants.js
  test/mocks/AppStubPinnedStorage.sol
  test/mocks/AppStubStorage.sol
  test/unstructured_storage.js
Labels: epic: audit, sprint: 0.5.5

#390 EVMScriptRegistry: emit events on adding and disabling executors
  contracts/evmscript/EVMScriptRegistry.sol
Labels: epic: in sprint addition

#391 EVMScriptExecutor: add type for off-chain reading
  contracts/evmscript/IEVMScriptExecutor.sol
  contracts/evmscript/executors/CallsScript.sol
  test/evm_script.js
  test/keccak_constants.js
  test/mocks/KeccakConstants.sol
Labels: epic: in sprint addition

#376 Move AragonApp to unstructured storage
  contracts/acl/ACL.sol
  contracts/apm/APMRegistry.sol
  contracts/apps/AppProxyBase.sol
  contracts/apps/AppProxyPinned.sol
  contracts/apps/AppProxyUpgradeable.sol
  contracts/apps/AppStorage.sol
  contracts/apps/AragonApp.sol
  contracts/common/Initializable.sol
  contracts/common/TimeHelpers.sol
  contracts/common/UnstructuredStorage.sol
  contracts/evmscript/EVMScriptRunner.sol
  test/keccak_constants.js
  test/mocks/AppStubPinnedStorage.sol
  test/mocks/AppStubStorage.sol
  test/mocks/KeccakConstants.sol
  test/unstructured_storage.js
Labels: breaking-change, enhancement, sprint: 0.5.4, sprint: 0.5.5

#351 ACL: use more explicit nonces to calculate the role and params hash
  contracts/acl/ACL.sol
Labels: breaking-change, epic: in sprint addition, sprint: 0.5.3, sprint: 0.5.4, sprint: 0.5.5

#386 Petrifiable: add tests
  migrations/2_apm.js
  migrations/3_factory.js
  test/apm_registry.js
  test/apm_repo.js
  test/app_acl.js
  test/app_base_lifecycle.js
  test/app_proxy.js
  test/ens_subdomains.js
  test/evm_script.js
  test/helpers/assertThrow.js
  test/helpers/onlyIf.js
  test/kernel_acl.js
  test/kernel_apps.js
  test/kernel_lifecycle.js
  test/kernel_upgrade.js
  test/lifecycle.js
  test/mocks/APMRegistryFactoryMock.sol
  test/mocks/AppStub.sol
  test/mocks/AppStubConditionalRecovery.sol
  test/mocks/AppStubStorage.sol
  test/mocks/ERCProxyMock.sol
  test/mocks/LifecycleMock.sol
  test/mocks/MockScriptExecutorApp.sol
  test/mocks/UnsafeAragonAppMock.sol
  test/mocks/UnsafeRepo.sol
  test/mocks/UpgradedKernel.sol
  test/proxy_recover_funds.js
  test/unstructured_storage.js
Labels: audit: cd, epic: audit, sprint: 0.5.5

#355 Add petrifiable
  contracts/acl/ACL.sol
  contracts/apm/APMRegistry.sol
  contracts/apm/Repo.sol
  contracts/apps/AragonApp.sol
  contracts/apps/UnsafeAragonApp.sol
  contracts/common/Autopetrified.sol
  contracts/common/Initializable.sol
  contracts/common/Petrifiable.sol
  contracts/evmscript/EVMScriptRegistry.sol
  contracts/evmscript/EVMScriptRunner.sol
  contracts/evmscript/executors/BaseEVMScriptExecutor.sol
  contracts/evmscript/executors/CallsScript.sol
  contracts/factory/APMRegistryFactory.sol
  contracts/kernel/Kernel.sol
  migrations/2_apm.js
  migrations/3_factory.js
  test/TestACLInterpreter.sol
  test/apm_registry.js
  test/apm_repo.js
  test/app_acl.js
  test/app_base_lifecycle.js
  test/app_proxy.js
  test/ens_subdomains.js
  test/evm_script.js
  test/helpers/assertThrow.js
  test/helpers/onlyIf.js
  test/kernel_acl.js
  test/kernel_apps.js
  test/kernel_lifecycle.js
  test/kernel_upgrade.js
  test/lifecycle.js
  test/mocks/APMRegistryFactoryMock.sol
  test/mocks/AppStub.sol
  test/mocks/AppStubConditionalRecovery.sol
  test/mocks/AppStubStorage.sol
  test/mocks/ERCProxyMock.sol
  test/mocks/LifecycleMock.sol
  test/mocks/MockScriptExecutorApp.sol
  test/mocks/UnsafeAragonAppMock.sol
  test/mocks/UnsafeRepo.sol
  test/mocks/UpgradedKernel.sol
  test/proxy_recover_funds.js
  test/unstructured_storage.js
Labels: audit: cd, breaking-change, epic: audit, sprint: 0.5.3, sprint: 0.5.4, sprint: 0.5.5

#393 DAOFactory: clarify permissions clean up
  contracts/factory/DAOFactory.sol
Labels: epic: in sprint addition

#394 Proxies: add checks for base being a contract
  contracts/apps/AppProxyPinned.sol
  contracts/common/Initializable.sol
  contracts/kernel/KernelProxy.sol
  test/app_proxy.js
  test/keccak_constants.js
  test/kernel_apps.js
  test/kernel_upgrade.js
  test/mocks/AppStubPinnedStorage.sol
  test/mocks/KernelOverloadMock.sol
  test/mocks/KernelSetAppMock.sol
  test/unstructured_storage.js
Labels: epic: audit

#387 Add bytecode manager and current bytecode to diff against
  .gitignore
  package.json
Labels: epic: audit, sprint: 0.5.5

#392 EVMScriptRegistry: add ability to re-enable disabled executors
  contracts/evmscript/EVMScriptRegistry.sol
  contracts/factory/DAOFactory.sol
  contracts/factory/EVMScriptRegistryFactory.sol
  contracts/test/mocks/EVMScriptExecutorMock.sol
  contracts/test/mocks/KeccakConstants.sol
  test/evm_script.js
  test/keccak_constants.js
Labels: breaking-change, epic: in sprint addition

#397 Use auth modifier for createPermissions
  contracts/acl/ACL.sol
Labels: acl

#407 ACL: add notes about lifecycle safety
  contracts/acl/ACL.sol
Labels: epic: audit, type: docs
