Repository aragon/aragonOS, pull requests merged in 2018-07, with the labels that each got.

#344 Add SafeMath lib for uint8
  contracts/lib/zeppelin/math/SafeMath8.sol
Labels: enhancement, sprint: 0.5.2, status: quick-review-and-merge

#348 Explicitly state state visibility
  contracts/acl/ACL.sol
  contracts/apm/APMRegistry.sol
  contracts/apm/Repo.sol
Labels: audit: cd, epic: audit, sprint: 0.5.3

#354 Add test task to Travis CI
  .travis.yml
  scripts/ganache-cli.sh
Labels: epic: in sprint addition, sprint: 0.5.3

#347 Kernel: remove kernelIntegrity modifier
  contracts/kernel/Kernel.sol
  test/kernel_apps.js
Labels: audit: cd, epic: audit, sprint: 0.5.3

#359 Make fallbacks external
  contracts/common/DepositableDelegateProxy.sol
  contracts/lib/minime/MiniMeToken.sol
  test/mocks/EncodeMock.sol
  test/mocks/VaultMock.sol
Labels: sprint: 0.5.3

#350 EVMScriptRunner: add ScriptResult log
  contracts/evmscript/EVMScriptRunner.sol
  test/evm_script.js
Labels: audit: cd, epic: audit, sprint: 0.5.3

#357 Add more static contract types to state and function parameters
  .solcover.js
  contracts/acl/ACL.sol
  contracts/acl/IACLOracle.sol
  contracts/evmscript/EVMScriptRegistry.sol
  contracts/evmscript/EVMScriptRunner.sol
  contracts/evmscript/IEVMScriptRegistry.sol
  contracts/factory/DAOFactory.sol
  contracts/factory/EVMScriptRegistryFactory.sol
  contracts/kernel/Kernel.sol
  contracts/kernel/KernelProxy.sol
  contracts/lib/minime/MiniMeToken.sol
  test/TestACLInterpreter.sol
  test/TestAclOracle.sol
  test/helpers/ACLHelper.sol
Labels: audit: cd, epic: audit, sprint: 0.5.3

#373 Clean package
  .gitignore
  package-lock.json
  package.json
Labels: epic: in sprint addition, sprint: 0.5.4

#371 Coverage: fix proxy_recover_funds tests failing due to vault being behind a proxy
  test/helpers/coverage.js
  test/mocks/VaultMock.sol
  test/proxy_recover_funds.js
Labels: epic: in sprint addition, sprint: 0.5.4

#356 [Prototype] Check for initialization during access control check
  contracts/apps/AragonApp.sol
  contracts/common/Initializable.sol
  contracts/kernel/Kernel.sol
Labels: audit: cd, epic: audit, sprint: 0.5.3
